service: piyal-demo-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  profile: piyal-demo-profile

plugins:
  - serverless-s3-sync
  - serverless-webpack

package:
  individually: true

custom:
  s3Sync:
    - bucketName: piyal-demo-bucket-789
      localDir: UploadData

functions:
  getUsers:
    handler: lambdas/getData.handler
    events:
      - http:
          path: /getUsers
          method: GET
          cors: true

resources:
  Resources:
    PiyalBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: piyal-demo-bucket-789
