service: piyal-demo-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  profile: piyal-demo-profile

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: piyal-demo-bucket-789
      localDir: UploadData

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    PiyalBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: piyal-demo-bucket-789
